Review manual and update
dev-academy-programme/orientation pull request #9
Opened 2016-10-25 21:53 UTC by richchurcher

This began as a move of all info subdirectories back into the main tree, at Jaime's suggestion here:

https://trello.com/c/neb1tL4G/11-move-the-subdirectories-of-important-course-information-into-the-same-directory-as-everything-else-so-that-all-the-links-e-g-our

However, there were many areas that hadn't been kept up to date. Even our Phase 0 rollback email addresses included one from Dev Bootcamp!

It's a slightly annoying PR to review because most directories have been renamed. Let me know if I can clarify anything.

Points covered:
1. Spell check, naming consistency, formatting.
2. Occasional grammar fixes.
3. Updating any information that implies rolling cohorts to suggest static cohorts.
4. Updating email addresses.
5. Fix broken links.
6. Re-label 3 agreements as 3 pillars, since that seems to be our current name for them.
7. Remove numbers from directory names, because it makes them too brittle (all links break when we change the order of something).

2016-10-26 00:59 UTC, don-smith requested changes
Looks like this was long overdue. Nice work (as always)!

2016-10-26 00:59 UTC, locksmithdon commented on pairing/README.md
>  Pairing [doesn't feel natural or easy for everyone](http://blogs.atlassian.com/2009/06/pair_programming_is_kryptonite/). We ask that you keep an open-mind on pairing throughout EDA and challenge your
_open mind_ instead of _open-mind_?

2016-10-26 00:59 UTC, locksmithdon commented on three-pillars/README.md
>  We also expect every person to be kind to one another. Kindness does not mean "nice;" they are actually not the same thing. Being kind does mean being friendly, generous, and considerate, but it does
I don't think we need to bold the first letter of each word, but even if we do, we can use markdown.

2016-10-26 00:59 UTC, locksmithdon commented on use-of-space/README.md
>  ## What support is available @ Dev Academy?
@ :arrow_right: _at_?

2016-10-27 02:18 UTC, richchurcher commented
Thanks! Always a few I miss ;)

2016-10-30 20:55 UTC, don-smith approved these changes

2016-10-30 20:56 UTC, merged